version: '3'

services:
  landwatch:
    build: .
    command: sh ./landwatch.sh
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.landwatch_env
      - ./.env

  db:
    image: ${POSTGRES_IMAGE_NAME}
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONT_PORT}"

  pgadmin:
    image: ${PGADMIN_IMAGE_NAME}
    restart: always
    depends_on:
      - db
    ports:
      - "${PGADMIN_HOST_PORT}:${PGADMIN_CONT_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:
